services:
    fpm:
        build:
            context: .
            dockerfile: Dockerfile.fpm
        ports:
            - "9500:80"
        volumes:
            - ./src:/usr/share/nginx/html/src
            - ./tests:/usr/share/nginx/html/tests
        networks:
            - testing
        depends_on:
            - swoole
    swoole:
        build:
            context: .
            dockerfile: Dockerfile.swoole
        ports: 
            - "9501:80"
        volumes:
            - ./dev:/usr/src/code/dev:rw
            - ./src:/usr/src/code/src
            - ./tests:/usr/src/code/tests
            - ./tmp/xdebug:/tmp/xdebug
        networks:
            - testing
networks:
  testing: